In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

In [3]:
df = sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop('species',axis = 1)
y = df['species']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
model_knn = KNeighborsClassifier() #for k=13 the model is overfitting

In [11]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [12]:
# y_pred = model_knn.predict(X_test)
# accuracy_score(y_test,y_pred)

In [13]:
model_knn.score(X_test,y_test) #gives the same thing as above two lines in the previous cell. It is a shortcut for the above two lines. It gives the accuracy score directly.

0.98

In [14]:
from sklearn.svm import SVC

In [15]:
model_svm = SVC(gamma= 'auto') #overfitting for C=10

In [16]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [17]:
model_svm.score(X_test,y_test)

1.0

# GridSearchCV

In [18]:
#now lets use the grid search CV

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
classifier_SVM = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},cv = 5,return_train_score = True)

In [21]:
classifier_SVM.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']},
             return_train_score=True)

In [22]:
classifier_SVM.cv_results_

{'mean_fit_time': array([0.00161214, 0.00110826, 0.00150819, 0.00120821, 0.00150871,
        0.00130806, 0.00120444, 0.00099912]),
 'std_fit_time': array([3.67805844e-04, 5.88866314e-04, 3.12480867e-04, 2.47499689e-04,
        6.40637474e-04, 6.11294499e-04, 4.01332917e-04, 1.51240840e-06]),
 'mean_score_time': array([0.00141134, 0.00131254, 0.00111356, 0.00131054, 0.00069828,
        0.00090775, 0.00123696, 0.00090613]),
 'std_score_time': array([0.0003747 , 0.00040553, 0.00021686, 0.00060197, 0.00059881,
        0.00049688, 0.00039536, 0.00049624]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32),
 'split0_train_score': array([0.98333333, 0.975     , 0.975     , 0.96666667, 0.96666667,
        0.975     , 0.975     , 0.975     ]),
 'split1_train_score': array([0.98333333, 0.975     , 0.96666667, 0.96666667, 0.975     ,
        0.96666667, 0.96666667, 0.975     ]),
 'split2_train_score': array([0.99166667, 0.99166667, 0.99166667, 0.99166667, 0.99166667,
        0.99166667, 0.99166667, 0.99166667]),
 'split3_train_score': array([0.98333333, 0.98333333, 0.98333333, 0.99166667, 0.99166667,
        1.        , 0.99166667, 1.        ]),
 'split4_train_score': array([0.975     , 0.98333333, 0.96666667, 0.975     , 0.975     ,
        0.975     , 0.98333333, 0.975     ]),
 'mean_train_score': array([0.98333333, 0.98166667, 0.97666667, 0.97833333, 0.98      ,
        0.98166667, 0.98166667, 0.98333333]),
 'std_train_score': array([0.00527046, 0.0062361 , 0.00971825, 0.01130388, 0.01      ,
        0.01224745, 0.00971825, 0.01054093])}

In [23]:
results_SVM = pd.DataFrame(classifier_SVM.cv_results_)

In [24]:
results_SVM

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,0.001612,0.000368,0.001411,0.000375,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,...,0.980000,0.016330,1,0.983333,0.983333,0.991667,0.983333,0.975000,0.983333,0.005270
1,0.001108,0.000589,0.001313,0.000406,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,...,0.980000,0.016330,1,0.975000,0.975000,0.991667,0.983333,0.983333,0.981667,0.006236
2,0.001508,0.000312,0.001114,0.000217,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,...,0.980000,0.016330,1,0.975000,0.966667,0.991667,0.983333,0.966667,0.976667,0.009718
3,0.001208,0.000247,0.001311,0.000602,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,...,0.973333,0.038873,4,0.966667,0.966667,0.991667,0.991667,0.975000,0.978333,0.011304
4,0.001509,0.000641,0.000698,0.000599,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,...,0.966667,0.036515,5,0.966667,0.975000,0.991667,0.991667,0.975000,0.980000,0.010000
5,0.001308,0.000611,0.000908,0.000497,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,...,0.966667,0.042164,6,0.975000,0.966667,0.991667,1.000000,0.975000,0.981667,0.012247
6,0.001204,0.000401,0.001237,0.000395,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,...,0.960000,0.038873,7,0.975000,0.966667,0.991667,0.991667,0.983333,0.981667,0.009718
7,0.000999,0.000002,0.000906,0.000496,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,...,0.960000,0.048990,7,0.975000,0.975000,0.991667,1.000000,0.975000,0.983333,0.010541

In [25]:
results_SVM.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_C', 'param_kernel', 'params', 'split0_test_score',
       'split1_test_score', 'split2_test_score', 'split3_test_score',
       'split4_test_score', 'mean_test_score', 'std_test_score',
       'rank_test_score', 'split0_train_score', 'split1_train_score',
       'split2_train_score', 'split3_train_score', 'split4_train_score',
       'mean_train_score', 'std_train_score'],
      dtype='object')

In [26]:
results_SVM[['param_C','param_kernel','mean_test_score','mean_train_score']] #mean train vs mean test scores gives shows if the model is overfitting or not. If the mean train score is much higher than the mean test score then the model is overfitting. If they are close to each other then the model is not overfitting.

   param_C param_kernel  mean_test_score  mean_train_score
0        1          rbf         0.980000          0.983333
1        1       linear         0.980000          0.981667
2       10          rbf         0.980000          0.976667
3       10       linear         0.973333          0.978333
4       20          rbf         0.966667          0.980000
5       20       linear         0.966667          0.981667
6       30          rbf         0.960000          0.981667
7       30       linear         0.960000          0.983333

In [27]:
classifier_SVM.best_params_ #gives the best parameters for the model. It gives the parameters that gives the highest mean test score.

{'C': 1, 'kernel': 'rbf'}

In [28]:
classifier_knn = GridSearchCV((model_knn),{
    'n_neighbors' : [1,3,5,7,9,11,13],
    'weights' : ['uniform','distance'],
    'algorithm' : ['auto','ball_tree','kd_tree','brute'],
    'metric' : ['euclidean','manhattan','minkowski']
},cv = 7,return_train_score = True)

In [29]:
classifier_knn.fit(X,y)

GridSearchCV(cv=7, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [1, 3, 5, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             return_train_score=True)

In [30]:
results_knn = pd.DataFrame(classifier_knn.cv_results_)

In [31]:
results_knn

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_weights,params,split0_test_score,...,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,split5_train_score,split6_train_score,mean_train_score,std_train_score
0,0.001646,0.000593,0.002944,0.001349,auto,euclidean,1,uniform,"{'algorithm': 'auto', 'metric': 'euclidean', '...",0.954545,...,125,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
1,0.001222,0.000755,0.001539,0.000686,auto,euclidean,1,distance,"{'algorithm': 'auto', 'metric': 'euclidean', '...",0.954545,...,125,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
2,0.001079,0.000176,0.002074,0.000179,auto,euclidean,3,uniform,"{'algorithm': 'auto', 'metric': 'euclidean', '...",0.954545,...,35,0.960938,0.953125,0.968750,0.961240,0.968992,0.953488,0.953488,0.960003,0.006458
3,0.001429,0.000496,0.000933,0.000165,auto,euclidean,3,distance,"{'algorithm': 'auto', 'metric': 'euclidean', '...",0.954545,...,35,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
4,0.001345,0.000540,0.002406,0.000442,auto,euclidean,5,uniform,"{'algorithm': 'auto', 'metric': 'euclidean', '...",0.954545,...,67,0.968750,0.960938,0.976562,0.976744,0.976744,0.968992,0.968992,0.971103,0.005493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,0.001803,0.000592,0.005205,0.000777,brute,minkowski,9,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.954545,...,67,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
164,0.001977,0.000941,0.010542,0.012121,brute,minkowski,11,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.954545,...,1,0.984375,0.984375,0.984375,0.976744,0.992248,0.976744,0.968992,0.981122,0.006980
165,0.001643,0.000582,0.005185,0.000494,brute,minkowski,11,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.954545,...,1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
166,0.001719,0.000756,0.007177,0.001557,brute,minkowski,13,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.909091,...,35,0.984375,0.976562,0.984375,0.976744,0.984496,0.976744,0.976744,0.980006,0.003819
167,0.002339,0.000849,0.006030,0.000928,brute,minkowski,13,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.954545,...,17,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000

In [32]:
results_knn[['param_n_neighbors','mean_test_score','mean_train_score']]

     param_n_neighbors  mean_test_score  mean_train_score
0                    1         0.960111          1.000000
1                    1         0.960111          1.000000
2                    3         0.966914          0.960003
3                    3         0.966914          1.000000
4                    5         0.966605          0.971103
..                 ...              ...               ...
163                  9         0.966605          1.000000
164                 11         0.980210          0.981122
165                 11         0.980210          1.000000
166                 13         0.966914          0.980006
167                 13         0.973408          1.000000

[168 rows x 3 columns]

In [33]:
classifier_knn.best_params_

{'algorithm': 'auto',
 'metric': 'euclidean',
 'n_neighbors': 11,
 'weights': 'uniform'}

In [34]:
from sklearn.model_selection import RandomizedSearchCV

In [35]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},n_iter = 4,cv = 5,return_train_score = False)

In [36]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [37]:
results = pd.DataFrame(classifier_r.cv_results_)

In [38]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002013,0.000021,0.001849,0.000487,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002251,0.000677,0.001700,0.000882,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,3
2,0.002083,0.000350,0.001206,0.000683,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,4
3,0.001702,0.000745,0.001623,0.000509,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [39]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1       10       linear         0.973333
2       20          rbf         0.966667
3       10          rbf         0.980000